# Generated by Django 3.2.9 on 2021-11-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.FileField(blank=True, default='skills/default.png', null=True, upload_to='skills'),
        ),
    ]
